### ISSUE TITLE
file devise.rb causes the issue to start server on localhost and create db

### ISSUE THREAD

**Issue by webqatutor** [alex-videll/chess#1]
- attempt to create db causes the issue with following logs
```
Caused by:
NameError: uninitialized constant Devise
/vagrant/src/chess/config/initializers/devise.rb:5:in `<top (required)>'
/vagrant/src/chess/config/environment.rb:5:in `<top (required)>'
```
- the gemfile `devise` is not present in `Gemfile`.  The fix can be made by deleting `devise.rb` 
since this gem is not installed for the project.

**Comment by alex-videll** [comment]
We can delete the file and reinstall devise if that's ok with you.

**Comment by webqatutor** [comment]
done. I can run server on localhost now. I will reinstall devise with a new pull request.

**Comment by webqatutor** [comment]
opened pull request.

**Comment by webqatutor** [comment]
changes merged.
